# App name
spring.application.name=securetrade

# MySQL database connection
# make sure MySQL is running and database 'securetrade' is created
spring.datasource.url=jdbc:mysql://localhost:3306/securetrade
spring.datasource.username=root
spring.datasource.password=Aditya@0412

# JPA settings
# update = automatically creates/updates tables based on models
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# this is needed to avoid dialect warning in console
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect